# ------------------------------------------------------------------------------
# Compile R-Package Vignette
# Samuel Pawel
# 2019-12-09
# ------------------------------------------------------------------------------

build:
	echo "library('knitr'); knit2pdf('ReplicationSuccess.Rnw')" | R --no-save --no-restore

clean:
	rm -f *.dvi *.aux *.log *.toc *.bmt *.bbl *.blg *.idx *.ilg *.ind *.mtc* *.flc *.out *.nav *.vrb
